### ISSUE TITLE
Add keywords to Cargo.toml

### ISSUE THREAD

**Issue by fitzgen** [alekratz/enum-methods#15]
I effectively [reimplemented](https://github.com/fitzgen/derive_is_enum_variant) some functionality that exists in this crate because I didn't find it in a crates.io search :-P

Ideas:

* predicate
* variant
* derive
* is

**Comment by alekratz** [comment]
Heh, oops. Maybe I'll steal some ideas from your functionality :)

I'll add some of those keywords later today. Thanks for the heads-up.

**Comment by alekratz** [comment]
Also, if you (or anyone else) has any ideas for more keywords feel free to suggest them here (or make a PR, I super don't care).

**Comment by alekratz** [comment]
This was added in ccaaf72.
